name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
        architecture: "x64"
    - name: restorte cache
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: install requirements
      run: pip install -r requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install tox
    - name: tox
      run: |
        tox
